jobs:
  - deployment: Deploy
    condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/pull/')))
    displayName: Deploy
    environment: 'honghuackubernetesingress'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: git://nginx-pipeline-demo/nginx-pipeline-demo
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              kubernetesServiceConnection: 'test-nginx-ingress'
              action: deploy
              namespace: nginx-ingress
              manifests: |
                $(Pipeline.Workspace)/master/examples-of-custom-resources/traffic-splitting/cafe.yaml
                $(Pipeline.Workspace)/master/examples-of-custom-resources/traffic-splitting/cafe-virtual-server.yaml


