jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'honghuackubernetesingress'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: git://nginx-pipeline-demo/nginx-pipeline-demo
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              kubernetesServiceConnection: 'test-nginx-ingress'
              action: deploy
              namespace: default
              manifests: |
                $(Build.SourcesDirectory)/examples-of-custom-resources/traffic-splitting/cafe.yaml
                $(Build.SourcesDirectory)/examples-of-custom-resources/traffic-splitting/cafe-virtual-server.yaml


